name: test

on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    timeout-minutes: 40

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Declare env variables on push only
        if: github.event_name == 'push'
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Declare env variables on pull_request only
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$GITHUB_HEAD_REF" >> $GITHUB_ENV

      - name: Declare env variables on push and pull_request
        shell: bash
        if: github.event_name == 'push'
        run: |
          echo "QWE=PPPPUSH" >> $GITHUB_ENV
